config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # resources :tasks
  root to: "projects#index"

  resources :tasks do
    member do
      patch :up
      patch :down
    end
  end

  resources :projects
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/avatar_adapter.rb
# frozen_string_literal: true

class AvatarAdapter
  attr_accessor :user

  def initialize(user)
    @user = user
  end

  def client
    @client ||= Twitter::REST::Client.new(
        consumer_key: Rails.application.secrets.twitter_api_key,
        consumer_secret: Rails.application.secrets.twitter_api_secret,
      )
  end

  def image_url
    client.user(user.twitter_handle).profile_image_uri(:bigger).to_s
  end
end

app/models/concerns/sizeable.rb
module Sizeable
  extend ActiveSupport::Concern

  def small?
    size <= 1
  end

  def epic?
    size >= 5
  end
end

app/models/project.rb
class Project < ApplicationRecord
  include Sizeable

  has_many :tasks, -> { order "project_order ASC" }, dependent: :destroy
  validates :name, presence: true
  has_many :roles, dependent: :destroy
  has_many :users, through: :roles

  def self.velocity_length_in_days
    21
  end

  def incomplete_tasks
    tasks.reject(&:complete?)
  end

  def done?
    incomplete_tasks.empty?
  end

  def size
    tasks.sum(&:size)
  end

  def remaining_size
    incomplete_tasks.sum(&:size)
  end

  def completed_velocity
    tasks.sum(&:points_toward_velocity)
  end

  def current_rate
    completed_velocity * 1.0 / Project.velocity_length_in_days
  end

  def projected_days_remaining
    remaining_size / current_rate
  end

  def on_schedule?
    return false if projected_days_remaining.nan? || projected_days_remaining.infinite?

    (Time.zone.today + projected_days_remaining) <= due_date
  end

  def next_task_order
    return 1 if tasks.empty?

    (tasks.last.project_order || tasks.size) + 1
  end

  def self.all_public
    where(public: true)
  end
end

app/models/role.rb
class Role < ApplicationRecord
  belongs_to :user
  belongs_to :project
end

app/models/task.rb
class Task < ApplicationRecord
  include Sizeable
  belongs_to :project
  belongs_to :user, optional: true

  def mark_completed(date = Time.current)
    self.completed_at = date
  end

  def complete?
    completed_at.present?
  end

  def part_of_velocity?
    return false unless complete?

    completed_at > Project.velocity_length_in_days.days.ago
  end

  def points_toward_velocity
    part_of_velocity? ? size : 0
  end

  def first_in_project?
    return false unless project

    project.tasks.first == self
  end

  def last_in_project?
    return false unless project

    project.tasks.last == self
  end

  def previous_task
    project.tasks.find_by(project_order: project_order - 1)
  end

  def next_task
    project.tasks.find_by(project_order: project_order + 1)
  end

  def swap_order_with(other)
    other.project_order, self.project_order = project_order, other.project_order
    save
    other.save
  end

  def move_up
    swap_order_with(previous_task) unless first_in_project?
  end

  def move_down
    swap_order_with(next_task) unless last_in_project?
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable
  has_many :roles, dependent: :destroy
  has_many :projects, through: :roles
  has_many :tasks, dependent: :nullify

  def can_view?(project)
    project.in?(visible_projects)
  end

  def visible_projects
    return Project.all if admin?

    Project.where(id: project_ids).or(Project.all_public)
  end

  def avatar_url
    adapter = AvatarAdapter.new(self)
    adapter.image_url
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # protect_from_forgery with: :exception
  # before_action :authenticate_user!
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    @projects = current_user.visible_projects
  end

  def show
    @project = Project.find(params[:id])
    unless current_user.can_view?(@project)
      redirect_to new_user_session_path
      return
    end
    respond_to do |format|
      format.html {}
      format.js { render json: @project.as_json(root: true, include: :tasks) }
    end
  end

  def new
    @project = Project.new
  end

  def create
    @workflow = CreatesProject.new(name: params[:project][:name], task_string: params[:project][:tasks],
                                   users: [current_user])
    @workflow.create
    if @workflow.success?
      redirect_to projects_path
    else
      @project = @workflow.project
      render :new
    end
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :load_task, only: %i[up down]

  def create
    @project = Project.find(params[:task][:project_id])
    unless current_user.can_view?(@project)
      redirect_to new_user_session_path
      return
    end
    @project.tasks.create(task_params.merge(project_order: @project.next_task_order))
    redirect_to(@project)
  end

  def update
    @task = Task.find(params[:id])
    completed = params[:task][:completed] == "true" && !@task.complete?
    params[:task][:completed_at] = Time.current if completed
    if @task.update(task_params)
      TaskMailer.task_completed_email(@task).deliver if completed
      redirect_to @task, notice: "project was successfully updated"
    else
      render action :edit
    end
  end

  def up
    @task.move_up
    redirect_to(@task.project)
  end

  def down
    @task.move_down
    redirect_to(@task.project)
  end

  private

  def load_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:project_id, :title, :size)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
  def name_with_status(project)
    dom_class = project.on_schedule? ? "on_schedule" : "behind_schedule"
    content_tag(:span, project.name, class: dom_class)
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>TestRor</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
</head>

<body>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<%= yield %>
</body>
</html>

app/views/projects/index.html.erb
<h1>All Projects</h1>
<table>

  <thead>
  <tr>
    <td>Project Name</td>
    <td>Total Project Size</td>
  </tr>
  </thead>

  <tbody>
  <% @projects.each do |project| %>
    <tr class="project-row" id="<%= dom_id(project) %>">
      <td class="name"><%= name_with_status(project) %></td>
      <td class="total-size"><%= project.size %></td>
    </tr>
  <% end %>
  </tbody>

</table>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= form_for(@project) do |f| %>
  <%= f.label(:name) %>
  <%= f.text_field(:name) %>
  <br />
  <%= f.label(:tasks) %>
  <%= text_area_tag("project[tasks]") %>
  <br />
  <%= f.submit "Create Project" %>
<% end %>

app/views/projects/show.html.erb
<h2>Project <%= @project.name %></h2>

<h3>Existing Tasks:</h3>

<table>
  <thead>
  <tr>Name</tr>
  <tr>Size</tr>
  </thead>
  <tbody>
  <% @project.tasks.each do |task| %>
    <tr id="task_<%= task.project_order %>" data-task-id=<%= task.id %>>
      <td class="name"><%= task.title %></td>
      <td class="size"><%= task.size %></td>
<!--      <td class="completed"><%#= task.completed_at %></td>-->
      <td class="completed">
        <% if task.complete? %>
          <%= task.user.email %>
          <%= task.completed_at.to_s %>
          <img src="<%= task.user.avatar_url %>" />
        <% end %>
      </td>
      <td>
        <button class="up-button">Up</button>
        <button class="down-button">Down</button>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

<!--  <tbody>-->
  <%# @project.tasks.each do |task| %>
<!--    <tr id="task_<%#= task.project_order %>">-->
<!--      <td class="name"><%#= task.title %></td>-->
<!--      <td class="size"><%#= task.size %></td>-->
<!--      <td class="completed"><%#= task.completed_at %></td>-->
<!--      <td>-->
        <%# unless task.first_in_project? %>
          <%#= link_to "Up", up_task_path(task.id), method: :patch %>
        <%# end %>
        <%# unless task.last_in_project? %>
          <%#= link_to "Down", down_task_path(task.id), method: :patch %>
        <%# end %>
<!--      </td>-->
<!--    </tr>-->
  <%# end %>
<!--  </tbody>-->

<h3>New Task</h3>
<%= form_for Task.new(project_id: @project.id) do |f| %>
  <%= f.hidden_field :project_id %>
  <%= f.label :title, "Task" %>
  <%= f.text_field :title %>
  <%= f.label :size %>
  <%= f.select :size, [1, 2, 3, 4, 5] %>
  <%= f.submit "Add Task" %>
<% end %>